CMake: Add CMake support
ARMmbed/mbed-client-for-google-iot-cloud pull request #9
Opened 2020-11-18 21:15 UTC by rajkan01

- Added CMakeLists.txt file to Mbed client for google cloud so that it can able build via CMake
- Removed this `IOTC_MQTT_HOST` macro config from `mbed_lib.json` as this macro
  generated by `mbedtools` with double quotes `-DIOTC_MQTT_HOST="{"mqtt.2030.ltsapis.goog", IOTC_MQTT_PORT}"`
  and messing with macro substitution and this config is never going to change.

@0xc0170 @hugueskamba

2020-11-24 17:35 UTC, LDong-Arm approved these changes
LGTM

2020-11-24 17:37 UTC, LDong-Arm requested changes
Need to update
* ntp-client.lib
* wifi-ism43362.lib
* mbed-client-for-google-iot-cloud.lib once https://github.com/ARMmbed/mbed-client-for-google-iot-cloud/pull/9 is merged

2020-11-25 10:11 UTC, hugueskamba commented
>Removed this IOTC_MQTT_HOST macro config from mbed_lib.json as this macro
generated by mbedtools with double quotes -DIOTC_MQTT_HOST="{"mqtt.2030.ltsapis.goog", IOTC_MQTT_PORT}"

Shouldn't the tool be corrected?

2020-11-25 16:03 UTC, rajkan01 commented
> 
> 
> > Removed this IOTC_MQTT_HOST macro config from mbed_lib.json as this macro
> > generated by mbedtools with double quotes -DIOTC_MQTT_HOST="{"mqtt.2030.ltsapis.goog", IOTC_MQTT_PORT}"
> 
> Shouldn't the tool be corrected?

@hugueskamba Mbedtools is generating `-DIOTC_MQTT_HOST={"mqtt.2030.ltsapis.goog", IOTC_MQTT_PORT}` from `mbed_lib.json` config `IOTC_MQTT_HOST` config (MQTT host and port configuration) as like other config and CMake prepossessing time this macro gets divided into multiple `#define macros` because of host starts with `double-quotes`.
And I found that this config is redundant as this host and port is never going to change.

2020-11-26 09:35 UTC, 0xc0170 commented
> And I found that this config is redundant as this host and port is never going to change.

That does not mean others won't hit this issue? Can you review how " " should be done in macros ? If this is our bug, cmake bug or it is feature of CMake? Let's find out - create an issue with details please

2020-11-26 09:36 UTC, 0xc0170 approved these changes
+ new issue for "" - we might just need document this (this should be in migration guide as it changes between old and new tools)

2020-11-26 11:23 UTC, rajkan01 commented
> 
> 
>     * new issue for "" - we might just need document this (this should be in migration guide as it changes between old and new tools)

@0xc0170  Identified that this is an issue with `mbedtools` as it generates -D macro wrongly, created github issue to mbedtools repo https://github.com/ARMmbed/mbed-tools/issues/125. As mentioned earlier this `"iotc-mqtt-host"` which I removed from `mbed_lib.json` is no longer required as this parameter never change for google cloud

2020-11-26 11:36 UTC, rajkan01 commented
@evedon Could you review this PR Thanks

2020-11-26 12:49 UTC, evedon approved these changes

2020-11-26 12:49 UTC, evedon commented on mbed_lib.json
> -          "value": "{\"mqtt.2030.ltsapis.goog\", IOTC_MQTT_PORT}",
I see that this the default set in iot-device-sdk-embedded-c library
https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/blob/master/src/libiotc/iotc_config.h/#L47

2020-11-26 12:49 UTC, merged